Recycler added in RaceDetail
SugarDaddy322/F1CalendarApp pull request #2
Opened 2022-04-26 10:02 UTC by SugarDaddy322

Создал новый адаптер для Race detail с viewholder'ами под каждую сессию и заголовок. Переделал RaceDetailFragment.kt
Большую часть кода и данных для Race detail написал в RaceFunctions в getRaceDetailData

2022-04-26 12:09 UTC, AlexeyGvozdev commented
Давай придумывать более логичные названия веток

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +            TYPE_HEADER -> R.layout.item_detail_header
Сами по себе лейауты отличаются? Если нет, то замени на один

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +        const val TYPE_SESSION1 = 0
Тебе не обязательно заводить константы. Ты можешь вместо констант использовать R.layout.(твой лейаут)

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +                is RaceDetailModel.Header -> bindHeader(raceDetailModel)
Слишком много when. Кажется, что нужно переписать

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragmentNEW.kt
> +class RaceDetailFragmentNEW : Fragment(R.layout.fragment_race_detail2) {
Зачем завёл новый фрагмент? Почему в старом нельзя было сделать?

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragmentNEW.kt
> +        val race = arguments?.getSerializable(RaceListFragment.RACE_DATE_KEY) as RaceF1
Я бы добавил прогресс на экран пока грузим данные

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailModel.kt
> +    data class Session1(
Несколько одинаковых классов. Зачем?

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        fun getRaceDetailData(race: RaceF1): ArrayList<RaceDetailModel>{
Скажи, почему лучше возвращать `List<RaceDetailModel>`

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +    private val raceList = ArrayList<RaceF1>()
Почему здесь ArrayList а не List?

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +        val recyclerView: RecyclerView = view.findViewById(R.id.recyclerView) // recyclerview init
такие комментарии лучше удалять)

2022-04-26 13:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +    private val racesAdapter: RacesAdapter by lazy {RacesAdapter(this) }
у тебя разметка поехала не хватает пробела

2022-04-27 10:53 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +    private val racesAdapter: RacesAdapter by lazy {RacesAdapter(this) }
Исрпавил

2022-04-27 10:54 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +        val recyclerView: RecyclerView = view.findViewById(R.id.recyclerView) // recyclerview init
Есть такое))

2022-04-27 10:55 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailModel.kt
> +    data class Session1(
В голове была путанница что раз несколько viewholder ов, то значит и для каждого всё прописывать. В общем убрал

2022-04-27 10:56 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragmentNEW.kt
> +        val race = arguments?.getSerializable(RaceListFragment.RACE_DATE_KEY) as RaceF1
То есть прогресс бар? Или как?

2022-04-27 10:57 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragmentNEW.kt
> +class RaceDetailFragmentNEW : Fragment(R.layout.fragment_race_detail2) {
Решил создать новый файл, там всё записать с нуля, потому что ничего одинакового почти не было, но забыл переименовать его

2022-04-27 10:58 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +        const val TYPE_SESSION1 = 0
Сделано

2022-04-27 10:58 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +            TYPE_HEADER -> R.layout.item_detail_header
Убрал лишние

2022-04-27 14:18 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        fun getRaceDetailData(race: RaceF1): ArrayList<RaceDetailModel>{
Потому что List служит только как read-only и не может быть модифицирован. А значит меньше лишнего доступа и возможно легче

2022-04-27 14:18 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +    private val raceList = ArrayList<RaceF1>()
Сам не знаю, но если мои догадки насчёт List выше правильные, то поменяю

2022-04-27 14:25 UTC, sdtf322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +                is RaceDetailModel.Header -> bindHeader(raceDetailModel)
Убрал ненужные строчки

2022-04-28 06:18 UTC, AlexeyGvozdev requested changes

2022-04-28 06:18 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +        val TYPE_SESSION = R.layout.item_detail_session
Константы можно убрать. Чтобы было так when(viewType) { R.layout.item_detail_session -> {...} ...}

2022-04-28 06:19 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        fun getRaceDetailData(race: RaceF1): ArrayList<RaceDetailModel>{
Да, верно. Не стоит давать клиентам возможность менять список

2022-04-29 10:26 UTC, merged

2022-04-29 10:31 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +        val TYPE_SESSION = R.layout.item_detail_session
Сделал