Wip retrofit detail
SugarDaddy322/F1CalendarApp pull request #5
Opened 2022-06-05 11:36 UTC by SugarDaddy322

Добавлен ретрофит, переделан RacesAdapter и onClickListener. В RaceFunctions() переделана функция для добавления данных(getDetailApiData()) для фрагмента RaceDetailFragment.kt, добавлены функции для форматирования дат и чисел и распознавания флагов для каждой отдельной гонки.

2022-06-05 12:16 UTC, AlexeyGvozdev requested changes

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/build.gradle
> +        minSdk 26
зачем поднял версию?

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.4.2'
тут тоже можно делать переменные `def navVersion = '2.4.2'` как то так можно

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WAKE_LOCK" />
Зачем тебе WAKE_LOCK?

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceApi.kt
> +    suspend fun getRaceInfo(): Response<RaceResponse>
Нельзя ли просто вернуть `RaceRecponse`? без `Response`

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
Давай сделаем так, чтобы фрагмент сам знал как класть данные в аргументы

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceModel.kt
> +        val RaceTable: RaceTable,
названия полей с большой буквы

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +open class RacesAdapter(private val onClickListener: OnClickListener) :
зачем open?

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    inner class MyViewHolder(val binding: ItemRaceListBinding) : RecyclerView.ViewHolder(binding.root)
Почему вьюхолдер в адаптере?
и зачем `inner class`?

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragment.kt
> +        val recyclerView : RecyclerView = view.findViewById(R.id.recyclerViewDetail)
в адаптере биндинг, а тут нет

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +        val race = raceList[position]
эту логику убираем в холдер

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    class OnClickListener(val clickListener: (race: Race) -> Unit) {
так делают в java, в kotlin можно проще. 
`class RacesAdapter(private val onClick: (Race) -> Unit))`

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    class OnClickListener(val clickListener: (race: Race) -> Unit) {
и класс `OnClickListener` не нужен

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RetrofitInstance.kt
> +        .setLenient()
без этого точно не работает?

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
>      RecyclerView.Adapter<RacesAdapter.MyViewHolder>() {
если используешь `DiffUtil`, то наследуйся от `RecyclerView.ListAdapter`

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    private val diffCallback = object : DiffUtil.ItemCallback<Race>(){
это в отдельный файл

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    private val raceFunctions = RaceFunctions()
так нельзя, какую-то логику из адаптера уносим. В адаптер кладём данные для отрисовки

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'
кажется это теперь лишнее

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +            raceFunctions.BindFlagByCountry(raceCountry, flagImage)
функция с большой буквы?

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        var flagDrawable = R.drawable.flag_austria
давай по дефолту будем какой-нибудь плейсхолдер использовать

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        when(country){ // Race Country
можно проще сделать 
flagDrawable = when(country) {
    "Bahrain" -> R.drawable.flag_bahrain
    ...
}

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        when(country){ // Race Country
и добавь else

2022-06-05 12:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +            raceFunctions.BindFlagByCountry(raceCountry, flagImage)
логику из адаптера уносим

2022-06-05 12:21 UTC, SugarDaddy322 commented on app/build.gradle
> +        minSdk 26
Для использования DateTimeFormatter

2022-06-05 13:07 UTC, AlexeyGvozdev commented on app/build.gradle
> +        minSdk 26
такое себе решение. Надо чтобы 21 апи поддерживалось

2022-06-05 13:11 UTC, SugarDaddy322 commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'
Верно, убрал

2022-06-05 13:13 UTC, SugarDaddy322 commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.WAKE_LOCK" />
Что-то экспериментировал, не помню, в общем пока-что убрал это

2022-06-05 13:22 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceModel.kt
> +        val RaceTable: RaceTable,
![image](https://user-images.githubusercontent.com/80196043/172052608-a7842433-30b9-4900-9b68-7f1ab80c4f26.png)
Когда поменял все поля с маленькой буквы, снова начало эту ошибку выдавать

2022-06-05 13:30 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +open class RacesAdapter(private val onClickListener: OnClickListener) :
Здесь это и вправду лишнее, убрал

2022-06-05 13:35 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        when(country){ // Race Country
Сделал

2022-06-05 13:38 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceApi.kt
> +    suspend fun getRaceInfo(): Response<RaceResponse>
![image](https://user-images.githubusercontent.com/80196043/172053427-45e732f9-8e92-40f2-bcf4-e0a0bd129566.png)
Ругается тогда(

2022-06-05 13:41 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RetrofitInstance.kt
> +        .setLenient()
Убрал .setLenient(), всё работает

2022-06-05 14:05 UTC, SugarDaddy322 commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-ui-ktx:2.4.2'
добавил nav_version и lifecycle_version

2022-06-05 14:07 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
То есть?

2022-06-05 14:08 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceApi.kt
> +    suspend fun getRaceInfo(): Response<RaceResponse>
значит убери эти проверки

2022-06-05 14:08 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceApi.kt
> +    suspend fun getRaceInfo(): Response<RaceResponse>
`val raceResponse: RaceResponse = response`

2022-06-05 14:09 UTC, SugarDaddy322 commented on app/build.gradle
> +        minSdk 26
Окей, переделаю под SimpleDateFormat

2022-06-05 14:09 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
Сделай так, чтобы создание фрагмента `RaceDetailFragment` было в `RaceDetailFragment`

2022-06-05 14:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceModel.kt
> +        val RaceTable: RaceTable,
погугли про @SerializableName

2022-06-05 14:10 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RetrofitInstance.kt
> +        .setLenient()
значит убери переменную gson

2022-06-05 14:12 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceApi.kt
> +    suspend fun getRaceInfo(): Response<RaceResponse>
Да, убрал, заработало

2022-06-05 14:17 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RetrofitInstance.kt
> +        .setLenient()
убрал, всё ок

2022-06-05 14:19 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceFunctions.kt
> +        var flagDrawable = R.drawable.flag_austria
Окей, попробую

2022-06-05 14:27 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    private val raceFunctions = RaceFunctions()
То есть, адаптер должен получить конечные данные для отрисовки, связать и чтобы внутри адаптера больше ничего бы не происходило?

2022-06-05 17:24 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    private val raceFunctions = RaceFunctions()
верно

2022-06-06 15:43 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    inner class MyViewHolder(val binding: ItemRaceListBinding) : RecyclerView.ViewHolder(binding.root)
Исправил

2022-06-06 15:43 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +        val race = raceList[position]
Исправил

2022-06-06 15:48 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    private val diffCallback = object : DiffUtil.ItemCallback<Race>(){
Сделал

2022-06-06 15:50 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +            raceFunctions.BindFlagByCountry(raceCountry, flagImage)
Исправил

2022-06-06 16:22 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceModel.kt
> +        val RaceTable: RaceTable,
Сделал

2022-06-06 16:36 UTC, sdtf322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
>      RecyclerView.Adapter<RacesAdapter.MyViewHolder>() {
Окей, переделал

2022-06-08 19:58 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
Нам же всё равно нужен RaceDetailFragment в листе, чтобы сделать переход фрагмента. Или для чего создавать RaceDetailFragment в самом RaceDetailFragment?

2022-06-09 06:49 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
Я не очень понимаю совсем. Что если это переделать под ViewModel, кстати?

2022-06-09 16:27 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
не, через вьюмодель не надо

2022-06-09 16:28 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
у тебя сейчас `RaceDetailFragment` знает как создаётся `RaceDetailFragment`. Можно это убрать в `RaceDetailFragment`

2022-06-09 16:34 UTC, AlexeyGvozdev requested changes

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/build.gradle
> +    id  'kotlin-kapt'
это зачем?

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/build.gradle
> +    def lifecycle_version = "2.4.1"
переменные перенеси ближе к месту использования

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
тут тоже сделай переменную

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.12.0'
и тут

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/MainActivity.kt
> +
удали строку

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailAdapter.kt
> +
верни как было

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListAdapter.kt
> +    var raceList : List<Race>
это уже не надо так делать ListAdapter сам это реализует

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListAdapter.kt
> +    override fun getItemCount(): Int {
ListAdapter сам это под капотом делает

2022-06-09 16:34 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +    private lateinit var raceListAdapter: RaceListAdapter
верни lazy

2022-06-09 17:11 UTC, SugarDaddy322 commented on app/build.gradle
> +    def lifecycle_version = "2.4.1"
окей

2022-06-09 17:11 UTC, SugarDaddy322 commented on app/build.gradle
> +    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
сделал

2022-06-09 17:12 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +    private lateinit var raceListAdapter: RaceListAdapter
вернул

2022-06-09 17:27 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListAdapter.kt
> +    var raceList : List<Race>
Хорошо

2022-06-09 17:27 UTC, SugarDaddy322 commented on app/build.gradle
> +    id  'kotlin-kapt'
убрал

2022-06-09 18:23 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragment.kt
> +        val recyclerView : RecyclerView = view.findViewById(R.id.recyclerViewDetail)
Сделал

2022-06-10 14:57 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
Всё равно не понимаю какие строчки убирать и вставлять в RaceDetailFragment. Здесь же вроде бы все нужно

2022-06-13 11:17 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
>          bundle.putSerializable(RACE_DATE_KEY, race)
Сделал

2022-06-13 11:17 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RacesAdapter.kt
> +    class OnClickListener(val clickListener: (race: Race) -> Unit) {
Сделал

2022-06-14 17:29 UTC, AlexeyGvozdev requested changes

2022-06-14 17:29 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragment.kt
> +                putSerializable(RACE_DATE_KEY, race)
почему не Parcelable?

2022-06-14 17:29 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceDetailViewHolder.kt
>          private val circuitImage : ImageView = itemView.findViewById(R.id.circuitImage)
у тебя же теперь тут биндинг

2022-06-14 17:29 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +        communicator.passRaceData(race)
можно и так сделать, но я бы просто сделал метод который открывает любой фрагмент. 
`communicator.openFragment(SomeFragment.newInstance(race))`

2022-06-14 17:29 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +        communicator.passRaceData(race)
просто с добавлением фрагментов у тебя начнёт расти количество методов в акстивити

2022-06-16 13:15 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailFragment.kt
> +                putSerializable(RACE_DATE_KEY, race)
Не знал про это, поменял

2022-06-16 13:15 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceDetailViewHolder.kt
>          private val circuitImage : ImageView = itemView.findViewById(R.id.circuitImage)
Да, точно

2022-06-16 13:16 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListFragment.kt
> +        communicator.passRaceData(race)
Я тоже думал, что в моём варианте нужен был бы метод для каждого фрагмента, но не знал как это переделать. Поменял

2022-06-16 13:35 UTC, merged