Wip MVVM
SugarDaddy322/F1CalendarApp pull request #8
Opened 2022-07-01 13:20 UTC by SugarDaddy322

Добавлен RaceListViewModel в проект, переделан RaceListFragment под MVVM

2022-07-04 06:40 UTC, AlexeyGvozdev requested changes

2022-07-04 06:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListViewModel.kt
> +    val raceList = MutableLiveData<List<Race>>()
у тебя наружу точит изменяемая лайвдата. Сделай чтобы фрагмент видел LIveData<List<Race>>

2022-07-04 06:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/RaceListViewModel.kt
> +            catch (e: IOException){
очень странные переносы строк у тебя

2022-07-05 11:07 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListViewModel.kt
> +    val raceList = MutableLiveData<List<Race>>()
Исправил

2022-07-05 11:08 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/RaceListViewModel.kt
> +            catch (e: IOException){
Исправил

2022-07-05 11:43 UTC, merged