Wip clean architecture
SugarDaddy322/F1CalendarApp pull request #9
Opened 2022-07-29 10:12 UTC by SugarDaddy322

Сделаны слои domain, presentation, data. Добавлены 2 use case:  GetRaceList, GetRaceDetailById(пустой). добавлены RaceRepository и RacfeRepositoryImpl. Добавлена отдельная модель RaceResponse в data слой

2022-08-02 17:30 UTC, AlexeyGvozdev requested changes

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/RaceStorageInterface.kt
> +interface RaceStorageInterface {
RaceRepository

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/models/RaceResponse.kt
> +    constructor(parcel: Parcel) : this(
удалить

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/models/RaceResponse.kt
> +    constructor(parcel: Parcel) : this(
удалить

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/models/RaceResponse.kt
> +
@Parcelize

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/network/RaceNetworkData.kt
> +class RaceNetworkData {
RaceRepositoryImpl : RaceRepository

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/network/RaceNetworkStorage.kt
> +        for(item in mutableRaceList){
Бизнес логика

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/network/RaceNetworkStorage.kt
> +class RaceNetworkStorage : RaceStorageInterface {
raceNetworkData должно быть в конструторе

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/repository/RaceRepositoryImpl.kt
> +class RaceRepositoryImpl(private val raceStorageInterface: RaceStorageInterface) : RaceRepository {
retrofitApi
flagStorage
dateFormatter 
должны быть тут

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/repository/RaceRepositoryImpl.kt
> +        val dataRaceList = runBlocking {
runBlocking удалить

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/repository/RaceRepositoryImpl.kt
> +    override fun getRaceList(): List<RaceModel> {
override suspend fun getRaceList() = retrofitApi.getRaceList()

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/domain/models/RaceModel.kt
> +        @SerializedName("Circuit")val circuit: Circuit,
@SerializedName("Circuit") удалить

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/domain/repository/RaceRepository.kt
> +    fun getRaceList() : List<RaceModel>
suspend

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/domain/usecases/GetRaceList.kt
> +class GetRaceList(private val raceRepository: RaceRepository) {
RaceListUseCase

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/domain/usecases/GetRaceList.kt
> +    fun execute() : List<RaceModel> {
operator suspend fun invoke()

2022-08-02 17:30 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/presentation/racelist/RaceListViewModel.kt
> +
private val getRaceList by lazy { GetRaceList(RaceRepositoryImpl(RaceNetworkStorage())) }

2022-08-04 18:40 UTC, AlexeyGvozdev requested changes

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/network/RaceNetworkData.kt
> +                deferredResponse.await()
логика в месте где её не должно быть

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/RaceStorageInterface.kt
> +interface RaceStorageInterface {
всё таки это лишний класс. У тебя уже есть интерфейс. RaceApi. Его используй взамен

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/network/RaceNetworkData.kt
> +        supervisorScope {
скоуп тут не нужен у тебя же `suspend fun`

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/repository/DateRepositoryImpl.kt
> +        val firstSessionDate = formatDate(race.firstPractice.date)
а это очень похоже на юзкейз. Ты же не делаешь запрос в сеть и ничего не сохраняешь в бд

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/repository/RaceRepositoryImpl.kt
> +class RaceRepositoryImpl(private val raceStorageInterface: RaceStorageInterface) : RaceRepository {
Я тебе тут подсказал что должно быть в конструкторе

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/data/repository/RaceRepositoryImpl.kt
> +class RaceRepositoryImpl(private val raceStorageInterface: RaceStorageInterface) : RaceRepository {
всё кроме dateFormatter

2022-08-04 18:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/f1calendarOP/domain/usecases/GetRaceDetailByIdUseCase.kt
> +class GetRaceDetailByIdUseCase {
удалить

2022-08-04 19:18 UTC, SugarDaddy322 commented on app/src/main/java/com/example/f1calendarOP/data/network/RaceNetworkData.kt
> +                deferredResponse.await()
try catch перенести в ViewModel?

2022-08-06 09:08 UTC, merged